### PR TITLE
Issue #895: Gradle fix

### PR DESCRIPTION
**Pull request by martemen**
A fix for the ForgeGradle compilation error from #895.

**Changes:**

- Updated the Gradle versions from 3.0 to 4.4.1
- Changed the ForgeGradle from the official to [anatawa12's fork](https://github.com/anatawa12/ForgeGradle-1.2)
- Changed the encoding to Unicode

### CODE REVIEW

**Comment by Toshayo** [comment]
Isn't https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/pull/858 doing the same? :)

**Comment by Toshayo** [comment]
My fork does not change encoding to Unicode though

**Comment by martemen** [comment]
My fix works with Gradle 4.4.1. 7.4.2 has many [deprecations](https://docs.gradle.org/current/javadoc/deprecated-list.html).

**Comment by HbmMods** [comment]
I know next to nothing about gradle so I'm not sure what PR to merge, what even is the functional difference between gradle versions? And has this been tested with Eclipse?

**Comment by martemen** [comment]
@HbmMods It wasn't tested with Eclipse but I do expect this to work.
@Toshayo Which pull request you prefer? Do you prefer to combine my changes with yours in PR #858?

**Comment by Toshayo** [comment]
I think @martemen gradle fix is better because:
 - it does not use a random maven found on the net
 - the gradle version has less deprecations

However, I think exporting all variables like version and stuff may be handy. Actually, I think it is to @HbmMods to decide if they prefer the old way of specifying version or the gradle.properties one :).

For now I'll test the fix with Eclipse, though I'm pretty sure there will be no problems with

**Comment by martemen** [comment]
> I think @martemen gradle fix is better because:
> 
> * it does not use a random maven found on the net
> * the gradle version has less deprecations
> 
> However, I think exporting all variables like version and stuff may be handy. Actually, I think it is to @HbmMods to decide if they prefer the old way of specifying version or the gradle.properties one :).
> 
> For now I'll test the fix with Eclipse, though I'm pretty sure there will be no problems with

**Thank you!**

**Comment by Toshayo** [comment]
Everything works as expected.
 - The project loads
 - External dependencies are present
 - Project builds
 - Runs are runnable
Used Eclipse 2020-06 (4.16.0)

**Comment by martemen** [comment]
@Toshayo I added Gradle properties, although I removed certain parameters like Minecraft versions, or mod versions because most of those won't probably be updated (the[ lasted forge 1.7.10 release](https://files.minecraftforge.net/net/minecraftforge/forge/index_1.7.10.html) is 7 years old).

**Review by Toshayo — APPROVED** [review]
I'm closing my PR
